language: cpp

sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On"
  matrix:
    - CMAKE_CONFIGURATION=release BUILD_DIR=build

matrix:
  exclude:
  - os: osx
    compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make
